<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Mercado.BL.BE\Mercado.BL.BE.csproj" />
    <ProjectReference Include="..\Mercado.DL.DALC\Mercado.DL.DALC.csproj" />
  </ItemGroup>
</Project>
